/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat Mar  3 13:02:55 PST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbGCD.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbGCD::MODEL_mkTbGCD()
{
  mkTbGCD_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbGCD()
{
  MODEL_mkTbGCD *model = new MODEL_mkTbGCD();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbGCD &INST_top = *((MOD_mkTbGCD *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_state_1_EQ_0___d14;
	 tUInt32 DEF_INST_top_DEF_b__h522;
	 DEF_INST_top_DEF_b__h522 = INST_top.INST_state.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_bounce = DEF_INST_top_DEF_b__h522 == 2u;
	 INST_top.DEF_WILL_FIRE_RL_bounce = INST_top.DEF_CAN_FIRE_RL_bounce;
	 INST_top.DEF_gcd_bz__h760 = INST_top.INST_gcd_bz.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_gcd_subtract = INST_top.DEF_gcd_bz__h760;
	 INST_top.DEF_WILL_FIRE_RL_gcd_subtract = INST_top.DEF_CAN_FIRE_RL_gcd_subtract;
	 INST_top.DEF_CAN_FIRE_RL_init = DEF_INST_top_DEF_b__h522 == 4294967295u;
	 INST_top.DEF_WILL_FIRE_RL_init = INST_top.DEF_CAN_FIRE_RL_init;
	 DEF_INST_top_DEF_state_1_EQ_0___d14 = DEF_INST_top_DEF_b__h522 == 0u;
	 INST_top.DEF_NOT_gcd_bz___d13 = !(INST_top.DEF_gcd_bz__h760);
	 INST_top.DEF_CAN_FIRE_RL_req = INST_top.DEF_NOT_gcd_bz___d13 && DEF_INST_top_DEF_state_1_EQ_0___d14;
	 INST_top.DEF_WILL_FIRE_RL_req = INST_top.DEF_CAN_FIRE_RL_req;
	 INST_top.DEF_b__h566 = INST_top.INST_c2.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_terminate = (INST_top.DEF_b__h566) == (tUInt8)63u && DEF_INST_top_DEF_state_1_EQ_0___d14;
	 INST_top.DEF_WILL_FIRE_RL_terminate = INST_top.DEF_CAN_FIRE_RL_terminate;
	 INST_top.DEF_CAN_FIRE_RL_resp = primSLT8(1u,
						  7u,
						  (tUInt8)(INST_top.DEF_b__h566),
						  7u,
						  (tUInt8)63u) && DEF_INST_top_DEF_b__h522 == 1u;
	 INST_top.DEF_WILL_FIRE_RL_resp = INST_top.DEF_CAN_FIRE_RL_resp;
	 if (INST_top.DEF_WILL_FIRE_RL_bounce)
	   INST_top.RL_bounce();
	 if (INST_top.DEF_WILL_FIRE_RL_init)
	   INST_top.RL_init();
	 if (INST_top.DEF_WILL_FIRE_RL_resp)
	   INST_top.RL_resp();
	 if (INST_top.DEF_WILL_FIRE_RL_gcd_subtract)
	   INST_top.RL_gcd_subtract();
	 if (INST_top.DEF_WILL_FIRE_RL_terminate)
	   INST_top.RL_terminate();
	 if (INST_top.DEF_WILL_FIRE_RL_req)
	   INST_top.RL_req();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_c1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_c2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gcd_x.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gcd_y.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gcd_bz.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbGCD::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbGCD_instance = new MOD_mkTbGCD(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbGCD_instance->set_clk_0)("CLK");
}
void MODEL_mkTbGCD::destroy_model()
{
  delete mkTbGCD_instance;
  mkTbGCD_instance = NULL;
}
void MODEL_mkTbGCD::reset_model(bool asserted)
{
  (mkTbGCD_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbGCD::get_instance()
{
  return mkTbGCD_instance;
}

/* Fill in version numbers */
void MODEL_mkTbGCD::get_version(unsigned int *year,
				unsigned int *month,
				char const **annotation,
				char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkTbGCD::get_creation_time()
{
  
  /* Sat Mar  3 21:02:55 UTC 2018 */
  return 1520110975llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkTbGCD::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkTbGCD::dump_state()
{
  (mkTbGCD_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbGCD & mkTbGCD_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbGCD *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbGCD(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbGCD::dump_VCD_defs()
{
  (mkTbGCD_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbGCD::dump_VCD(tVCDDumpType dt)
{
  (mkTbGCD_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbGCD_backing(sim_hdl));
}
